project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve-hierarchy: false

files:
    - source: /assets/i18n/strings.i18n.json
      translation: /assets/i18n/strings_%locale_with_underscore%.i18n.json
      dest: "ReVanced Manager/strings.i18n.json"
bundles:
    - 16
