name: Analyze Code

on:
  push:
    branches: dev
    paths: 
      - "**.dart"
      - ".github/workflows/analyze.yml"
  pull_request:
    branches: [ "main", "dev" ]
    paths: 
      - "**.dart"
      - ".github/workflows/analyze.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Generate files with Builder
        run: flutter packages pub run build_runner build --delete-conflicting-outputs
      - name: Analyze code
        uses: ValentinVignal/action-dart-analyze@v0.16
        with:
          fail-on: info
